//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileShareWeb.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileShareEntities : DbContext
    {
        public FileShareEntities()
            : base("name=FileShareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FILE_TABLE> FILE_TABLE { get; set; }
        public virtual DbSet<FOLDER_TABLE> FOLDER_TABLE { get; set; }
        public virtual DbSet<USER_TABLE> USER_TABLE { get; set; }
    }
}
