//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileShareWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE_TABLE
    {
        public System.Guid ID { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaUzantisi { get; set; }
        public long DosyaBoyutu { get; set; }
        public System.Guid FolderId { get; set; }
        public System.DateTime DosyayuklemeZamani { get; set; }
    
        public virtual FOLDER_TABLE FOLDER_TABLE { get; set; }
    }
}
