//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileShareWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLDER_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOLDER_TABLE()
        {
            this.FILE_TABLE = new HashSet<FILE_TABLE>();
        }
    
        public System.Guid ID { get; set; }
        public string KlasorAdi { get; set; }
        public System.Guid UserId { get; set; }
        public string KlasorAciklamasi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILE_TABLE> FILE_TABLE { get; set; }
        public virtual USER_TABLE USER_TABLE { get; set; }
    }
}
